version: '4.0.0'
kalash:
  description: >
    Test runner made for scalable automation
    based on standard Python's `unittest`
author: 'Product Testing Technica Engineering GmbH'
keywords: 
  - 'automation'
email: 'krzysztof.czarnecki@technica-engineering.de'
license: 'GPLv3'